### ISSUE TITLE
Integration of a polynomial with respect to a measure

### ISSUE THREAD

**Issue by tweisser** [JuliaAlgebra/MultivariateMoments.jl#15]
Would be nice to use `Measure` to integrate polynomials (and Numbers). Something like:
```julia
function integrate(p::MP.AbstractPolynomialLike, moms::MM.Measure)
    integral = 0.0
    for (c, m) in zip(coefficients(p), monomials(p))
        idx = findfirst(isequal(m), monomials(moms))
        integral += c*moms.a[idx]
    end
    return integral
end
```

**Comment by blegat** [comment]
It should be possible with `LinearAlgebra.dot` or `MultivariateMoments.expectation`:
https://github.com/JuliaAlgebra/MultivariateMoments.jl/blob/master/src/expectation.jl
https://juliaalgebra.github.io/MultivariateMoments.jl/stable/moments/#Expectation-1

**Comment by tweisser** [comment]
Thanks! That's what I was looking for.
